### PR TITLE
Fix Mysql CI

### PR DESCRIPTION
**Pull request by chadell**

### CODE REVIEW

**Review by jdrew82 — CHANGES_REQUESTED** [review]
LGTM, just needs the changelog snippet.

**Comment by chadell** [comment]
> LGTM, just needs the changelog snippet.

@jdrew82 , do you know why MySQL tests are not included in the CI???

**Comment by jdrew82** [comment]
> > LGTM, just needs the changelog snippet.
> 
> @jdrew82 , do you know why MySQL tests are not included in the CI???

I believe this was something related to the IPRange class which might not be relevant any longer. Can't hurt to enable them in CI and see.

**Comment by chadell** [comment]
> > > LGTM, just needs the changelog snippet.
> > 
> > 
> > @jdrew82 , do you know why MySQL tests are not included in the CI???
> 
> I believe this was something related to the IPRange class which might not be relevant any longer. Can't hurt to enable them in CI and see.

`MySQLdb.OperationalError: (1553, "Cannot drop index 'unique_with_index': needed in a foreign key constraint")` -> still there.

**Comment by jdrew82** [comment]
> > > > LGTM, just needs the changelog snippet.
> > > 
> > > 
> > > @jdrew82 , do you know why MySQL tests are not included in the CI???
> > 
> > 
> > I believe this was something related to the IPRange class which might not be relevant any longer. Can't hurt to enable them in CI and see.
> 
> `MySQLdb.OperationalError: (1553, "Cannot drop index 'unique_with_index': needed in a foreign key constraint")` -> still there.

Well that answers that then! Guess we need to leave MySQL support off for now until we figure out a solution.

**Comment by jdrew82** [comment]
@chadell any reason we shouldn't just close this and delete the branch?

**Comment by chadell** [comment]
let's close it

**Pull request closed without merging**
